# Generated by Django 5.2.1 on 2026-06-11 20:14

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0002_organization_approval_status_organization_website'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyAnalyticsSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('snapshot_date', models.DateField()),
                ('overview', models.JSONField(blank=True, default=dict)),
                ('funnel', models.JSONField(blank=True, default=dict)),
                ('time_to_hire', models.JSONField(blank=True, default=dict)),
                ('sources', models.JSONField(blank=True, default=dict)),
                ('team_activity', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics_snapshots', to='organizations.organization')),
            ],
            options={
                'ordering': ['-snapshot_date'],
                'indexes': [models.Index(fields=['organization', 'snapshot_date'], name='analytics_d_organiz_24f993_idx')],
                'constraints': [models.UniqueConstraint(fields=('organization', 'snapshot_date'), name='unique_daily_analytics_snapshot')],
            },
        ),
    ]
