# Generated by Django 5.2.1 on 2026-06-07 19:20

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('candidates', '0008_application_experience_score_application_final_score_and_more'),
        ('jobs', '0003_job_embedding_job_embedding_generated_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PipelineStage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('applied', 'Applied'), ('under_review', 'Under Review'), ('shortlisted', 'Shortlisted'), ('technical_round', 'Technical Round'), ('hr_round', 'HR Round'), ('offer', 'Offer'), ('rejected', 'Rejected'), ('hired', 'Hired')], default='applied', help_text='Canonical application status this stage maps to.', max_length=32)),
                ('order', models.PositiveIntegerField(default=0)),
                ('color', models.CharField(default='primary', max_length=32)),
                ('is_terminal', models.BooleanField(default=False)),
                ('auto_actions', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pipeline_stages', to='jobs.job')),
            ],
            options={
                'ordering': ['job', 'order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='PipelineStageHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notes', models.TextField(blank=True)),
                ('moved_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage_history', to='candidates.application')),
                ('from_stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='pipeline.pipelinestage')),
                ('moved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pipeline_stage_moves', to=settings.AUTH_USER_MODEL)),
                ('to_stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='pipeline.pipelinestage')),
            ],
            options={
                'ordering': ['moved_at'],
            },
        ),
        migrations.AddIndex(
            model_name='pipelinestage',
            index=models.Index(fields=['job', 'is_active', 'order'], name='pipeline_pi_job_id_cd0602_idx'),
        ),
        migrations.AddIndex(
            model_name='pipelinestage',
            index=models.Index(fields=['job', 'status'], name='pipeline_pi_job_id_c41364_idx'),
        ),
        migrations.AddConstraint(
            model_name='pipelinestage',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('job', 'order'), name='unique_active_pipeline_stage_order_per_job'),
        ),
        migrations.AddIndex(
            model_name='pipelinestagehistory',
            index=models.Index(fields=['application', 'moved_at'], name='pipeline_pi_applica_f5fbb5_idx'),
        ),
    ]
