# Generated by Django 5.2.1 on 2026-06-07 19:20

from django.db import migrations

DEFAULT_PIPELINE_STAGES = (
    {
        "name": "Applied",
        "status": "applied",
        "order": 10,
        "color": "primary",
        "is_terminal": False,
    },
    {
        "name": "Under Review",
        "status": "under_review",
        "order": 20,
        "color": "warning",
        "is_terminal": False,
    },
    {
        "name": "Shortlisted",
        "status": "shortlisted",
        "order": 30,
        "color": "sky",
        "is_terminal": False,
    },
    {
        "name": "Technical Round",
        "status": "technical_round",
        "order": 40,
        "color": "purple",
        "is_terminal": False,
    },
    {
        "name": "HR Round",
        "status": "hr_round",
        "order": 50,
        "color": "indigo",
        "is_terminal": False,
    },
    {
        "name": "Offer",
        "status": "offer",
        "order": 60,
        "color": "success",
        "is_terminal": False,
    },
    {
        "name": "Hired",
        "status": "hired",
        "order": 70,
        "color": "emerald",
        "is_terminal": True,
    },
    {
        "name": "Rejected",
        "status": "rejected",
        "order": 80,
        "color": "danger",
        "is_terminal": True,
    },
)


def seed_default_pipeline_stages(apps, schema_editor):
    Job = apps.get_model("jobs", "Job")
    Application = apps.get_model("candidates", "Application")
    PipelineStage = apps.get_model("pipeline", "PipelineStage")

    for job in Job.objects.all().iterator():
        if not PipelineStage.objects.filter(job=job, is_active=True).exists():
            PipelineStage.objects.bulk_create(
                PipelineStage(job=job, **stage_definition)
                for stage_definition in DEFAULT_PIPELINE_STAGES
            )

        first_stage_by_status = {}
        for stage in PipelineStage.objects.filter(job=job, is_active=True).order_by(
            "order",
            "created_at",
        ):
            first_stage_by_status.setdefault(stage.status, stage)

        for application in Application.objects.filter(job=job, current_stage__isnull=True):
            stage = first_stage_by_status.get(application.status)
            if stage:
                application.current_stage = stage
                application.save(update_fields=["current_stage"])


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0001_initial'),
        ('candidates', '0009_application_current_stage_and_more'),
    ]

    operations = [
        migrations.RunPython(seed_default_pipeline_stages, migrations.RunPython.noop),
    ]
