# Generated by Django 5.2.1 on 2026-06-11 15:38

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('candidates', '0010_candidatenote'),
        ('organizations', '0002_organization_approval_status_organization_website'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewQuestionSet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('ready', 'Ready'), ('error', 'Error')], default='ready', max_length=20)),
                ('model', models.CharField(blank=True, max_length=100)),
                ('source_context_hash', models.CharField(db_index=True, max_length=64)),
                ('generation_errors', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interview_question_sets', to='candidates.application')),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_interview_question_sets', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interview_question_sets', to='organizations.organization')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InterviewQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('technical', 'Technical'), ('behavioral', 'Behavioral'), ('situational', 'Situational'), ('culture_fit', 'Culture Fit'), ('gap_analysis', 'Gap Analysis')], max_length=30)),
                ('question_text', models.TextField()),
                ('rationale', models.TextField(blank=True)),
                ('evaluation_criteria', models.TextField(blank=True)),
                ('source', models.CharField(choices=[('ai', 'AI'), ('bank', 'Question Bank'), ('manual', 'Manual')], default='ai', max_length=20)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('is_pinned', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='interviews.interviewquestionset')),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuestionBankItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role_family', models.CharField(blank=True, max_length=100)),
                ('category', models.CharField(choices=[('technical', 'Technical'), ('behavioral', 'Behavioral'), ('situational', 'Situational'), ('culture_fit', 'Culture Fit'), ('gap_analysis', 'Gap Analysis')], max_length=30)),
                ('question_text', models.TextField()),
                ('evaluation_criteria', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='question_bank_items', to='organizations.organization')),
            ],
            options={
                'ordering': ['role_family', 'category', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='InterviewQuestionNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interview_question_notes', to=settings.AUTH_USER_MODEL)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='interviews.interviewquestion')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['question', 'created_at'], name='interviews__questio_a9b45c_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='interviewquestionset',
            index=models.Index(fields=['organization', 'application', 'created_at'], name='interviews__organiz_9f0cd5_idx'),
        ),
        migrations.AddIndex(
            model_name='interviewquestionset',
            index=models.Index(fields=['application', 'source_context_hash'], name='interviews__applica_97451c_idx'),
        ),
        migrations.AddIndex(
            model_name='interviewquestion',
            index=models.Index(fields=['question_set', 'category', 'order'], name='interviews__questio_671b13_idx'),
        ),
        migrations.AddIndex(
            model_name='questionbankitem',
            index=models.Index(fields=['organization', 'role_family', 'category'], name='interviews__organiz_685a01_idx'),
        ),
        migrations.AddIndex(
            model_name='questionbankitem',
            index=models.Index(fields=['is_active'], name='interviews__is_acti_265d7b_idx'),
        ),
    ]
