# Generated by Django 5.2.1 on 2026-05-29 19:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('action', models.CharField(db_index=True, help_text="Dot-namespaced action identifier, e.g. 'recruiter.approved'", max_length=100)),
                ('entity_type', models.CharField(blank=True, help_text="Model name of the affected entity, e.g. 'Recruiter', 'Organization'", max_length=100)),
                ('entity_id', models.CharField(blank=True, db_index=True, help_text='PK of the affected entity as string (supports UUIDs and BigInts)', max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional context — old/new values, reason, etc.')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of the acting user.', null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, help_text='The user who performed the action. Null for system actions.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
