# Generated by Django 5.2.1 on 2026-06-14 17:55

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batch', '0001_initial'),
        ('organizations', '0002_organization_approval_status_organization_website'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='batchjob',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('cancel_requested', 'Cancel Requested'), ('canceled', 'Canceled'), ('completed', 'Completed'), ('completed_with_errors', 'Completed with Errors'), ('failed', 'Failed')], db_index=True, default='pending', max_length=30),
        ),
        migrations.CreateModel(
            name='ScheduledBatchOperation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('job_type', models.CharField(choices=[('upload', 'Bulk Upload'), ('score', 'Batch Score'), ('pipeline_action', 'Pipeline Action')], max_length=30)),
                ('params', models.JSONField(blank=True, default=dict)),
                ('frequency', models.CharField(choices=[('once', 'Once'), ('daily', 'Daily'), ('weekly', 'Weekly')], default='once', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('next_run_at', models.DateTimeField(db_index=True)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduled_batch_operations', to=settings.AUTH_USER_MODEL)),
                ('last_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduled_sources', to='batch.batchjob')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_batch_operations', to='organizations.organization')),
            ],
            options={
                'ordering': ['next_run_at'],
                'indexes': [models.Index(fields=['organization', 'is_active', 'next_run_at'], name='batch_sched_organiz_a0f58d_idx')],
            },
        ),
    ]
