# Generated by Django 5.2.1 on 2026-05-30 08:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('candidates', '0001_initial'),
        ('jobs', '0001_initial'),
        ('organizations', '0002_organization_approval_status_organization_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='jobs.job'),
        ),
        migrations.AddField(
            model_name='application',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='application',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='candidates.candidate'),
        ),
        migrations.AddIndex(
            model_name='candidate',
            index=models.Index(fields=['organization', 'email'], name='candidates__organiz_deb685_idx'),
        ),
        migrations.AddConstraint(
            model_name='candidate',
            constraint=models.UniqueConstraint(fields=('organization', 'email'), name='unique_candidate_email_per_organization'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['organization', 'job'], name='candidates__organiz_a0e868_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['organization', 'status'], name='candidates__organiz_d91799_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['applied_at'], name='candidates__applied_93209b_idx'),
        ),
        migrations.AddConstraint(
            model_name='application',
            constraint=models.UniqueConstraint(fields=('candidate', 'job'), name='unique_application_candidate_job'),
        ),
    ]
