# Generated by Codex on 2026-05-30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("candidates", "0004_resume"),
    ]

    operations = [
        migrations.AddField(
            model_name="resume",
            name="application",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="resumes",
                to="candidates.application",
            ),
        ),
    ]
