# Generated by Django 5.2.1 on 2026-05-30 19:50

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0005_resume_application'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParsedResume',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('schema_version', models.PositiveSmallIntegerField(default=1)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('error', 'Error')], db_index=True, default='pending', max_length=20)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('confidence', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='low', max_length=20)),
                ('parser_model', models.CharField(blank=True, max_length=100)),
                ('validation_errors', models.JSONField(blank=True, default=list)),
                ('token_usage', models.JSONField(blank=True, default=dict)),
                ('estimated_cost', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('parsed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parsed_resumes', to='candidates.application')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parsed_resumes', to='candidates.candidate')),
                ('resume', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parsed_resume', to='candidates.resume')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['candidate', 'status'], name='candidates__candida_8b376b_idx'), models.Index(fields=['application', 'status'], name='candidates__applica_fe13cd_idx')],
            },
        ),
    ]
