# Generated by Django 5.2.1 on 2026-06-04 18:23

import pgvector.django.extensions
import pgvector.django.indexes
import pgvector.django.vector
from django.db import migrations, models


class PostgresOnlyHnswIndex(migrations.AddIndex):
    def database_forwards(self, app_label, schema_editor, from_state, to_state):
        if schema_editor.connection.vendor == "postgresql":
            super().database_forwards(app_label, schema_editor, from_state, to_state)

    def database_backwards(self, app_label, schema_editor, from_state, to_state):
        if schema_editor.connection.vendor == "postgresql":
            super().database_backwards(app_label, schema_editor, from_state, to_state)


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0006_parsedresume'),
    ]

    operations = [
        pgvector.django.extensions.VectorExtension(),
        migrations.AddField(
            model_name='parsedresume',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=384, null=True),
        ),
        migrations.AddField(
            model_name='parsedresume',
            name='embedding_generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parsedresume',
            name='embedding_model',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='parsedresume',
            name='embedding_text_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        PostgresOnlyHnswIndex(
            model_name='parsedresume',
            index=pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['embedding'], m=16, name='parsed_resume_embedding_hnsw', opclasses=['vector_cosine_ops']),
        ),
    ]
