# Generated by Django 5.2.1 on 2026-06-04 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0007_parsedresume_embedding_and_more'),
        ('jobs', '0003_job_embedding_job_embedding_generated_at_and_more'),
        ('organizations', '0002_organization_approval_status_organization_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='experience_score',
            field=models.DecimalField(blank=True, decimal_places=5, help_text='Normalized experience match score from 0.0 to 1.0.', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='final_score',
            field=models.DecimalField(blank=True, db_index=True, decimal_places=5, help_text='Weighted normalized candidate ranking score from 0.0 to 1.0.', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='score_calculated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='score_version',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='application',
            name='semantic_score',
            field=models.DecimalField(blank=True, decimal_places=5, help_text='Normalized semantic similarity score from 0.0 to 1.0.', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='skill_score',
            field=models.DecimalField(blank=True, decimal_places=5, help_text='Normalized skill match score from 0.0 to 1.0.', max_digits=6, null=True),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['organization', 'job', 'final_score'], name='applications_job_score_idx'),
        ),
    ]
