# Generated by Django 5.2.1 on 2026-06-07 19:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0008_application_experience_score_application_final_score_and_more'),
        ('jobs', '0003_job_embedding_job_embedding_generated_at_and_more'),
        ('organizations', '0002_organization_approval_status_organization_website'),
        ('pipeline', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='current_stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='pipeline.pipelinestage'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['organization', 'current_stage'], name='candidates__organiz_d41feb_idx'),
        ),
    ]
