# Generated by Django 5.2.1 on 2026-06-11 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0010_candidatenote'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='source',
            field=models.CharField(choices=[('direct', 'Direct'), ('job_board', 'Job Board'), ('linkedin', 'LinkedIn'), ('referral', 'Referral'), ('agency', 'Agency'), ('other', 'Other')], db_index=True, default='direct', help_text='Where the application originated (for source-effectiveness analytics).', max_length=20),
        ),
    ]
