# Generated by Django 5.2.15 on 2026-06-15 16:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0011_application_source'),
        ('jobs', '0003_job_embedding_job_embedding_generated_at_and_more'),
        ('organizations', '0002_organization_approval_status_organization_website'),
        ('pipeline', '0002_seed_default_pipeline_stages'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['organization', 'source'], name='candidates__organiz_58eb83_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['organization', 'job', 'status', 'applied_at'], name='candidates__organiz_c3abbb_idx'),
        ),
        migrations.AddIndex(
            model_name='applicationhistory',
            index=models.Index(fields=['application', 'changed_at'], name='candidates__applica_97483b_idx'),
        ),
        migrations.AddIndex(
            model_name='applicationhistory',
            index=models.Index(fields=['changed_by', 'changed_at'], name='candidates__changed_129a5b_idx'),
        ),
        migrations.AddIndex(
            model_name='applicationhistory',
            index=models.Index(fields=['to_status', 'changed_at'], name='candidates__to_stat_82901b_idx'),
        ),
        migrations.AddIndex(
            model_name='candidate',
            index=models.Index(fields=['organization', 'last_name', 'first_name'], name='candidates__organiz_44eab3_idx'),
        ),
        migrations.AddIndex(
            model_name='candidate',
            index=models.Index(fields=['organization', 'created_at'], name='candidates__organiz_c08dd0_idx'),
        ),
        migrations.AddIndex(
            model_name='resume',
            index=models.Index(fields=['application', 'file_hash'], name='candidates__applica_4c6d17_idx'),
        ),
    ]
