# Generated by Django 5.2.1 on 2026-05-29 19:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_role_recruiter'),
        ('organizations', '0002_organization_approval_status_organization_website'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recruiter',
            name='organization_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='organization_id',
        ),
        migrations.AddField(
            model_name='recruiter',
            name='first_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='recruiter',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='Denormalized flag — True when verification_status == approved.'),
        ),
        migrations.AddField(
            model_name='recruiter',
            name='last_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='recruiter',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recruiters', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='recruiter',
            name='title',
            field=models.CharField(blank=True, help_text="Job title, e.g. 'Senior Recruiter'", max_length=150),
        ),
        migrations.AddField(
            model_name='recruiter',
            name='verification_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('suspended', 'Suspended')], db_index=True, default='pending', max_length=16),
        ),
        migrations.AddField(
            model_name='user',
            name='is_email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='recruiter',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recruiter_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('recruiter', 'Recruiter'), ('hiring_manager', 'Hiring Manager'), ('interviewer', 'Interviewer'), ('candidate', 'Candidate')], default='recruiter', max_length=32),
        ),
    ]
