# Generated by Django 5.2.1 on 2026-05-30 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_recruiter_organization_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruiter',
            name='linkedin_profile',
            field=models.URLField(blank=True, help_text='LinkedIn profile URL. Required if company website is missing.', max_length=255),
        ),
    ]
