# Generated by Django 5.2.15 on 2026-06-15 16:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_job_embedding_job_embedding_generated_at_and_more'),
        ('organizations', '0002_organization_approval_status_organization_website'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['organization', 'status', 'created_at'], name='jobs_job_organiz_b88770_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['status', 'published_at'], name='jobs_job_status_d968cf_idx'),
        ),
    ]
