# Generated by Django 5.2.1 on 2026-05-29 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='approval_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('suspended', 'Suspended')], db_index=True, default='pending', max_length=16),
        ),
        migrations.AddField(
            model_name='organization',
            name='website',
            field=models.URLField(blank=True),
        ),
    ]
